### ISSUE TITLE
Licensing?

### ISSUE THREAD

**Issue by TAllenSr** [pozil/mongodb-jndi-datasource#4]
Hi there! We are looking to use your code within a commercial application. What is your licensing/permissions for this code? THANKS!

**Comment by pozil** [comment]
Hi,

Thanks for your interest in this project.
I have added an MIT license to it which means that you can use it free of charge in a commercial application as long as you give credits for it.

This license also exclude any form of warranty or liability. Note that I have not tested this project from some time (almost 2 years) and that I am no longer actively developing it.

That said, I hope that you will find this contribution useful. Good luck for your future work.

Cheers,
